metrics:
  - key: water_litres
    name: "water"
    unit: "litres"
  - key: calorie_kcal
    name: "calories"
    unit: "kilocalories"
  - key: sleep_hours
    name: "sleep"
    unit: "hours"
  - key: productivity_hours
    name: "productivity"
    unit: "hours"
  - key: exercise_hours
    name: "exercise"
    unit: "hours"